const GET_WEATHER = "GET_WEATHER";

const GET_COVID19_STAT = "GET_COVID19_STAT";

const GET_NEWS = "GET_NEWS";

const GET_YOUTUBE_TRENDING = "GET_YOUTUBE_TRENDING";

module.exports = {
  GET_NEWS,
  GET_COVID19_STAT,
  GET_WEATHER,
  GET_YOUTUBE_TRENDING,
};
